from uuid import UUID

import pytest

from app.models.memos import Memo
from app.repos.memos import MemoRepository


class TestMemoRepositoryIntegration:
    @pytest.fixture
    def memo_repo(self):
        return MemoRepository()

    @pytest.fixture
    async def sample_memo_data(self, session):
        """Test memo data"""
        memo = Memo(
            category="test",
            title="Integration Test Memo",
            contents="This is a test memo for integration testing"
        )
        session.add(memo)
        await session.commit()
        await session.refresh(memo)
        return memo

    async def test_get_by_pk_with_real_db(self, memo_repo, session, sample_memo_data):
        """Test querying by PK with real database"""
        # Execute
        result = await memo_repo.get_by_pk(session, sample_memo_data.id)

        # Verify
        assert result is not None
        assert result.id == sample_memo_data.id
        assert result.title == sample_memo_data.title
        assert result.contents == sample_memo_data.contents
        assert result.category == sample_memo_data.category

    async def test_get_by_pk_not_found_with_real_db(self, memo_repo, session):
        """Test querying for non-existent PK"""
        # Execute
        result = await memo_repo.get_by_pk(session, UUID("550e8400-e29b-41d4-a716-446655440000"))

        # Verify
        assert result is None

    async def test_get_with_where_condition(self, memo_repo, session, sample_memo_data):
        """Test query with WHERE condition"""
        # Execute
        result = await memo_repo.get(
            session,
            where=[Memo.title == "Integration Test Memo"]
        )

        # Verify
        assert result is not None
        assert result.id == sample_memo_data.id
        assert result.title == "Integration Test Memo"

    async def test_query_generation_validation(self, memo_repo, session):
        """Validate query generation logic"""
        # Check query generated by _select method
        stmt = memo_repo._select(where=[Memo.category == "test"])

        # Verify query string
        query_str = str(stmt.compile(compile_kwargs={"literal_binds": True}))
        assert "SELECT" in query_str
        assert "memos" in query_str
        assert "category" in query_str
        assert "ORDER BY" in query_str  # due to default_order_by_col

    async def test_primary_key_filters_generation(self, memo_repo):
        """Test primary key filter generation logic"""
        # Test single PK filter generation
        test_id = UUID("550e8400-e29b-41d4-a716-446655440000")
        filters = memo_repo._get_primary_key_filters(test_id)

        # Verify
        assert len(filters) == 1
        filter_str = str(filters[0])
        assert "memos.id" in filter_str
        # UUID is parameter bound, so placeholder appears instead of actual value
        assert ":id" in filter_str or "?" in filter_str
