services:
  backend:
    image: backend
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FIRST_USER_EMAIL: ${FIRST_USER_EMAIL:-admin@example.com}
      FIRST_USER_PASSWORD: ${FIRST_USER_PASSWORD:-admin}
      SECRET_KEY: ${SECRET_KEY:?SECRET_KEY-IS-REQUIRED}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-10}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7132/api/health" ]
      interval: 10s
      start_period: 10s
      timeout: 20s
      retries: 3
    ports:
      - 7132:7132