services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      PGUSER: ${POSTGRES_USER:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD-IS-REQUIRED}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: db
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

volumes:
  pg-data: