"""init

Revision ID: f726aef40502
Revises: f3853e463de7
Create Date: 2026-01-26 15:52:06.117447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f726aef40502'
down_revision: Union[str, None] = 'f3853e463de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memos', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('memos', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'memos', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'memos', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memos', type_='foreignkey')
    op.drop_constraint(None, 'memos', type_='foreignkey')
    op.drop_column('memos', 'updated_by')
    op.drop_column('memos', 'created_by')
    # ### end Alembic commands ###
